### PR TITLE
use install_name_tool to make sure that the anaconda libpython2.7.dylib ...

### PR DESCRIPTION
**Pull request by danielsf**
...can

find itself when installed on OSX

### CODE REVIEW

**Comment by danielsf** [comment]
I could do something like

if (Darwin)
    pythonName=$(ls $PREFIX/anaconda/lib/libpython*.dylib)
    install_name_tool -d $pythonName $pythonName

**Comment by ktlim** [comment]
Yes, that's along the lines of what I was thinking, but it may be overkill.  In particular, you need to protect against the case that there's more than one libpython for some reason.  Your decision.

**Comment by danielsf** [comment]
This makes me nervous but:

Is it worth considering running install_name_tool on all the .dylib files in anaconda?  GalSim can't be the only third party package that encounters this problem.

**Comment by ktlim** [comment]
libpython is pretty special: it is the only library that is used by external packages that has objects that need to be shared with anaconda Python.  I think in all other cases either we can locate the library via DYLD_LIBRARY_PATH every time we need to use it or we actually want to override the anaconda built-in.

**Comment by danielsf** [comment]
Okay.  I modified the script to run install_name_tool on any dylib file named libpython*.dylib

The ball is now in your court (i.e. I believe I have addressed all of your concerns)

Thanks.

**Pull request merged**
